"""adding student certificate start/end dates

Revision ID: 17d6eab75947
Revises: 25d5a168b8db
Create Date: 2015-09-13 16:45:20.129762

"""

# revision identifiers, used by Alembic.
revision = '17d6eab75947'
down_revision = '25d5a168b8db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_certificate_expires', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('student_certificate_received', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'student_certificate_received')
    op.drop_column('students', 'student_certificate_expires')
    ### end Alembic commands ###
