"""empty message

Revision ID: 1b8aa0869b8a
Revises: 1e241e281d4e
Create Date: 2015-07-19 13:36:02.247917

"""

# revision identifiers, used by Alembic.
revision = '1b8aa0869b8a'
down_revision = '1e241e281d4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
