"""add tsa eligibility for instructors

Revision ID: 1eb8fcd52b0c
Revises: 17d6eab75947
Create Date: 2015-09-13 16:57:01.280497

"""

# revision identifiers, used by Alembic.
revision = '1eb8fcd52b0c'
down_revision = '17d6eab75947'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('tsa_eligibility_doc_id', sa.Integer(), nullable=True))
    op.add_column('instructors', sa.Column('tsa_eligibility_doc_number', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'tsa_eligibility_doc_number')
    op.drop_column('instructors', 'tsa_eligibility_doc_id')
    ### end Alembic commands ###
