"""empty message

Revision ID: 1fa72956f0b0
Revises: 5956d8a11065
Create Date: 2015-07-05 20:34:28.724922

"""

# revision identifiers, used by Alembic.
revision = '1fa72956f0b0'
down_revision = '5956d8a11065'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    ### end Alembic commands ###
