"""re-adding tsa columns

Revision ID: 2082590ee0b9
Revises: 529d92609ea1
Create Date: 2015-09-13 14:11:12.582969

"""

# revision identifiers, used by Alembic.
revision = '2082590ee0b9'
down_revision = '529d92609ea1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'tsa_eligibility_confirmed')
    op.drop_column('students', 'tsa_eligibility_doc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('tsa_eligibility_doc', sa.INTEGER(), nullable=True))
    op.add_column('students', sa.Column('tsa_eligibility_confirmed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
