"""adding objectives and completion standards

Revision ID: 218b9548fd64
Revises: 220d08b5e390
Create Date: 2015-08-09 13:14:42.723012

"""

# revision identifiers, used by Alembic.
revision = '218b9548fd64'
down_revision = '220d08b5e390'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_lessons', sa.Column('completion_standards', sa.String(length=1024), nullable=True))
    op.add_column('flight_lessons', sa.Column('objectives', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_lessons', 'objectives')
    op.drop_column('flight_lessons', 'completion_standards')
    ### end Alembic commands ###
