"""add student PIC/solo time

Revision ID: 220d08b5e390
Revises: 496d7f143d6a
Create Date: 2015-07-25 17:53:57.658912

"""

# revision identifiers, used by Alembic.
revision = '220d08b5e390'
down_revision = '496d7f143d6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('student_pic_time', sa.Float(), nullable=True))
    op.add_column('flights', sa.Column('student_solo_time', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'student_solo_time')
    op.drop_column('flights', 'student_pic_time')
    ### end Alembic commands ###
