"""again, removing

Revision ID: 251ea3e574df
Revises: 2082590ee0b9
Create Date: 2015-09-13 16:38:16.201520

"""

# revision identifiers, used by Alembic.
revision = '251ea3e574df'
down_revision = '2082590ee0b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aircraft', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('flight_lessons', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('flights', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('instructors', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'roles', ['name'])
    op.alter_column('states', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    #op.drop_column('students', 'tsa_eligibility_doc_number')
    op.drop_column('students', 'tsa_eligibility_doc_id')
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('studenttypes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tests', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('testtypes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tsa_docs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tsa_docs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('testtypes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tests', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('studenttypes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('students', sa.Column('tsa_eligibility_doc_id', sa.TEXT(), nullable=True))
    op.add_column('students', sa.Column('tsa_eligibility_doc_number', sa.TEXT(), nullable=True))
    op.alter_column('states', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'roles')
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('instructors', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('flights', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('flight_lessons', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('aircraft', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
