"""and adding

Revision ID: 25d5a168b8db
Revises: 251ea3e574df
Create Date: 2015-09-13 16:38:40.405389

"""

# revision identifiers, used by Alembic.
revision = '25d5a168b8db'
down_revision = '251ea3e574df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('tsa_eligibility_doc_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('tsa_eligibility_doc_number', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'tsa_eligibility_doc_number')
    op.drop_column('students', 'tsa_eligibility_doc_id')
    ### end Alembic commands ###
