"""tsa docs: make column names clearer

Revision ID: 3179994f25ea
Revises: 28e461a1914d
Create Date: 2015-09-13 13:23:54.881423

"""

# revision identifiers, used by Alembic.
revision = '3179994f25ea'
down_revision = '28e461a1914d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('students', sa.Column('tsa_eligibility_doc_number', sa.String(length=128), nullable=True))
    #op.drop_column('students', 'tsa_eligibility_doc')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('students', sa.Column('tsa_eligibility_doc', sa.INTEGER(), nullable=True))
    #op.drop_column('students', 'tsa_eligibility_doc_number')
    ### end Alembic commands ###
    pass
