"""up to 32k characters for objectives and completion standards

Revision ID: 31aa32b00865
Revises: 317ea84a49bf
Create Date: 2015-08-24 23:53:50.498001

"""

# revision identifiers, used by Alembic.
revision = '31aa32b00865'
down_revision = '317ea84a49bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
