"""empty message

Revision ID: 324cb8ff4003
Revises: 456a945560f6
Create Date: 2015-07-05 17:45:54.196353

"""

# revision identifiers, used by Alembic.
revision = '324cb8ff4003'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.String(length=11), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('states')
    ### end Alembic commands ###
