"""medical for instructors

Revision ID: 335241f647af
Revises: 1eb8fcd52b0c
Create Date: 2015-09-13 17:03:51.982704

"""

# revision identifiers, used by Alembic.
revision = '335241f647af'
down_revision = '1eb8fcd52b0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('medical_expires', sa.Date(), nullable=True))
    op.add_column('instructors', sa.Column('medical_received', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'medical_received')
    op.drop_column('instructors', 'medical_expires')
    ### end Alembic commands ###
