"""empty message

Revision ID: 3fa0fd5a44c4
Revises: 4ead84050bb
Create Date: 2015-07-19 19:51:08.236304

"""

# revision identifiers, used by Alembic.
revision = '3fa0fd5a44c4'
down_revision = '4ead84050bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('flights_has_skills')
    #op.drop_table('skills')
    #op.add_column('testtypes', sa.Column('name', sa.String(length=32), nullable=True))
    #op.add_column('testtypes', sa.Column('scored', sa.Boolean(), nullable=True))
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testtypes', 'scored')
    op.drop_column('testtypes', 'name')
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights_has_skills',
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.Column('skill_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], [u'flights.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], [u'skills.id'], )
    )
    ### end Alembic commands ###
