"""add bfr for instructors

Revision ID: 4146939c5950
Revises: 58b642fa73fe
Create Date: 2015-09-13 17:54:02.735958

"""

# revision identifiers, used by Alembic.
revision = '4146939c5950'
down_revision = '58b642fa73fe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('bfr_expires', sa.Date(), nullable=True))
    op.add_column('instructors', sa.Column('bfr_received', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'bfr_received')
    op.drop_column('instructors', 'bfr_expires')
    ### end Alembic commands ###
