"""empty message

Revision ID: 4945f1b0e799
Revises: 523824fc5654
Create Date: 2015-07-19 14:47:53.333942

"""

# revision identifiers, used by Alembic.
revision = '4945f1b0e799'
down_revision = '523824fc5654'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
