"""adding ipc for instructors

Revision ID: 49d5d3c6a31c
Revises: 4146939c5950
Create Date: 2015-09-13 18:02:25.070240

"""

# revision identifiers, used by Alembic.
revision = '49d5d3c6a31c'
down_revision = '4146939c5950'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('ipc_expires', sa.Date(), nullable=True))
    op.add_column('instructors', sa.Column('ipc_received', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'ipc_received')
    op.drop_column('instructors', 'ipc_expires')
    ### end Alembic commands ###
