"""empty message

Revision ID: 4a9d90e4698a
Revises: 29232e09d1db
Create Date: 2015-07-19 15:47:26.966616

"""

# revision identifiers, used by Alembic.
revision = '4a9d90e4698a'
down_revision = '29232e09d1db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
