"""empty message

Revision ID: 4ac7a499af82
Revises: 324cb8ff4003
Create Date: 2015-07-05 18:14:38.960240

"""

# revision identifiers, used by Alembic.
revision = '4ac7a499af82'
down_revision = '324cb8ff4003'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
