"""empty message

Revision ID: 4c49ee321fa8
Revises: 43b04cc6a0b7
Create Date: 2015-07-19 16:03:55.293103

"""

# revision identifiers, used by Alembic.
revision = '4c49ee321fa8'
down_revision = '43b04cc6a0b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('testtypes', 'test_type')
    ### end Alembic commands ###


def downgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('testtypes', sa.Column('test_type', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
