"""all items to track for each flight

Revision ID: 4e1d9d87caea
Revises: 3fa0fd5a44c4
Create Date: 2015-07-19 22:05:12.875559

"""

# revision identifiers, used by Alembic.
revision = '4e1d9d87caea'
down_revision = '3fa0fd5a44c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tail_number', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'flights', sa.Column('aircraft_id', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('ftd', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('ground_time', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('ils', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('instrument_actual', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('instrument_hood', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('landings_day', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('landings_night', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('loc', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('me_dual', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('me_pic', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('ndb', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('night_dual', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('night_dual_xc', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('night_pic_solo', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('pcatd', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('rnav_gps', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('se_complex', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('se_dual', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('se_pic', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('se_solo', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('vor', sa.Integer(), nullable=True))
    op.add_column(u'flights', sa.Column('xc_dual', sa.Float(), nullable=True))
    op.add_column(u'flights', sa.Column('xc_pic_solo', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'flights', 'xc_pic_solo')
    op.drop_column(u'flights', 'xc_dual')
    op.drop_column(u'flights', 'vor')
    op.drop_column(u'flights', 'se_solo')
    op.drop_column(u'flights', 'se_pic')
    op.drop_column(u'flights', 'se_dual')
    op.drop_column(u'flights', 'se_complex')
    op.drop_column(u'flights', 'rnav_gps')
    op.drop_column(u'flights', 'pcatd')
    op.drop_column(u'flights', 'night_pic_solo')
    op.drop_column(u'flights', 'night_dual_xc')
    op.drop_column(u'flights', 'night_dual')
    op.drop_column(u'flights', 'ndb')
    op.drop_column(u'flights', 'me_pic')
    op.drop_column(u'flights', 'me_dual')
    op.drop_column(u'flights', 'loc')
    op.drop_column(u'flights', 'landings_night')
    op.drop_column(u'flights', 'landings_day')
    op.drop_column(u'flights', 'instrument_hood')
    op.drop_column(u'flights', 'instrument_actual')
    op.drop_column(u'flights', 'ils')
    op.drop_column(u'flights', 'ground_time')
    op.drop_column(u'flights', 'ftd')
    op.drop_column(u'flights', 'aircraft_id')
    op.drop_table('aircraft')
    ### end Alembic commands ###
