"""empty message

Revision ID: 4ead84050bb
Revises: abd909c94c4
Create Date: 2015-07-19 16:07:45.191793

"""

# revision identifiers, used by Alembic.
revision = '4ead84050bb'
down_revision = 'abd909c94c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
