"""empty message

Revision ID: 4edd3458f63d
Revises: 3fd240f86dac
Create Date: 2015-07-08 11:02:03.006157

"""

# revision identifiers, used by Alembic.
revision = '4edd3458f63d'
down_revision = '3fd240f86dac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
