"""empty message

Revision ID: 502f99d3cfb
Revises: 1fa72956f0b0
Create Date: 2015-07-05 21:32:39.206757

"""

# revision identifiers, used by Alembic.
revision = '502f99d3cfb'
down_revision = '1fa72956f0b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('flight_time', sa.Float(), nullable=True),
    sa.Column('flight_lesson_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_lesson_id'], ['flight_lessons.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights_has_skills',
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights_has_skills')
    op.drop_table('flights')
    ### end Alembic commands ###
