"""empty message

Revision ID: 51ca2914104c
Revises: 792d375c9
Create Date: 2015-07-19 16:01:36.074590

"""

# revision identifiers, used by Alembic.
revision = '51ca2914104c'
down_revision = '792d375c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('testtypes', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testtypes', sa.Column('name', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
