"""removing tsa columns

Revision ID: 529d92609ea1
Revises: 3179994f25ea
Create Date: 2015-09-13 14:09:19.788503

"""

# revision identifiers, used by Alembic.
revision = '529d92609ea1'
down_revision = '3179994f25ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('students', 'tsa_eligibility_confirmed')
    #op.drop_column('students', 'tsa_eligibility_doc')
    #op.drop_column('students', 'tsa_eligibility_doc_number')
    #op.drop_column('students', 'tsa_eligibility_doc_id')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('students', sa.Column('tsa_eligibility_doc_id', sa.VARCHAR(length=128), nullable=True))
    #op.add_column('students', sa.Column('tsa_eligibility_doc_number', sa.VARCHAR(length=128), nullable=True))
    #op.add_column('students', sa.Column('tsa_eligibility_doc', sa.INTEGER(), nullable=True))
    #op.add_column('students', sa.Column('tsa_eligibility_confirmed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
    pass
