"""specify autoincrement for instructors table

Revision ID: 563b43305f06
Revises: 57f8cfb36da8
Create Date: 2015-09-28 21:01:42.725196

"""

# revision identifiers, used by Alembic.
revision = '563b43305f06'
down_revision = '57f8cfb36da8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
