"""empty message

Revision ID: 56406ff43d
Revises: 4ac7a499af82
Create Date: 2015-07-05 19:54:22.286654

"""

# revision identifiers, used by Alembic.
revision = '56406ff43d'
down_revision = '4ac7a499af82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructors')
    ### end Alembic commands ###
