"""add flight review dates for instructors

Revision ID: 58b642fa73fe
Revises: 335241f647af
Create Date: 2015-09-13 17:12:41.749514

"""

# revision identifiers, used by Alembic.
revision = '58b642fa73fe'
down_revision = '335241f647af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('flight_review_expires', sa.Date(), nullable=True))
    op.add_column('instructors', sa.Column('flight_review_received', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructors', 'flight_review_received')
    op.drop_column('instructors', 'flight_review_expires')
    ### end Alembic commands ###
