"""empty message

Revision ID: 5c79244b6b3
Revises: 4a9d90e4698a
Create Date: 2015-07-19 15:58:02.053792

"""

# revision identifiers, used by Alembic.
revision = '5c79244b6b3'
down_revision = '4a9d90e4698a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testtypes', sa.Column('test_type', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('testtypes', 'scored')
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights_has_skills',
    sa.Column('flight_id', sa.INTEGER(), nullable=True),
    sa.Column('skill_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], [u'flights.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], [u'skills.id'], )
    )
    ### end Alembic commands ###
