"""empty message

Revision ID: 792d375c9
Revises: 5c79244b6b3
Create Date: 2015-07-19 16:00:26.827045

"""

# revision identifiers, used by Alembic.
revision = '792d375c9'
down_revision = '5c79244b6b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    pass
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('testtypes', 'test_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testtypes', sa.Column('test_type', sa.VARCHAR(length=32), nullable=True))
    ### end Alembic commands ###
