"""empty message

Revision ID: e9ab5cb3e2c
Revises: 4edd3458f63d
Create Date: 2015-07-08 11:16:02.167869

"""

# revision identifiers, used by Alembic.
revision = 'e9ab5cb3e2c'
down_revision = '4edd3458f63d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
